# Generated by Django 5.1.4 on 2025-04-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='lifetime_upload_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
